version: "3.9"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - myNetwork
  serv:
    build: .
    ports:
      - "5000:5000"
    networks:
      - myNetwork
    depends_on:
      - db
networks:
  myNetwork:
